language: android
sudo: false
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository
script:
- ./gradlew :app:assembleRelease
deploy:
  provider: releases
  user: "zhimei-HeiPo"
  password: "zxb_571533"
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true


